title: Discover and reuse projects within your organization
tagline: Discover and reuse projects within your organization
description: Discover and reuse projects within your organization
template:
  name: innersource
  repo: innersource-template
before:
- type: createIssue
  title: Welcome
  body: welcome.md

steps:

#1
- title: Close an issue
  description: Close an issue
  event: issues.closed
  actions:
  - type: createPullRequest
    title: Repository ownership and names
    head: repo-owner
    body: repo-owner.md
    action_id: ownerPR
  - type: respond
    with: goto-pr.md
    data: 
      url: '%actions.ownerPR.data.html_url%'

#2
- title: Answer the owner challenge
  description: Answer the owner challenge
  event: pull_request.edited
  actions:
  - type: respond
    with: repo-owner-answer.md

#3
- title: Merge the ownership PR
  description: Merge the ownership PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Create discoverable repos
    head: discoverable-repos
    body: discoverable.md
    action_id: discoverablePR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.discoverablePR.data.html_url%'  

#4
- title: Answer the discoverability challenge
  description: Answer the discoverability challenge
  event: issue_comment.created
  actions:
  - type: respond
    with: discoverability-answer.md

#5
- title: Merge the discoverability PR
  description: Merge the discoverability PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Issue and PR templates
    head: templates
    body: templates.md
    action_id: templatesPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.templatesPR.data.html_url%'

#6
- title: Answer the templates challenge question
  description: Answer the templates challenge question
  event: issue_comment.created
  actions:
  - type: respond
    with: templates-answer.md

#7
- title: Merge the templates PR
  description: Merge the templates PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Workflows
    head: workflows
    body: workflows.md
    action_id: workflowsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.workflowsPR.data.html_url%'

# 8: on issue_comment.created (learner answered)
#     - bot validates
#     - bot explains items in the PR, will be combinations of information about branch protections, example workflows, CODEOWNERS, deployment, etc
#     - asks learner to merge 
# 9: on pr.closed (learner merged)
#     - bot creates PR about Project management
#     - challenge: what should you work on? screenshot of issues
#     - learner chooses one
# 10: on issue_comment.edited (learner voted)
#     - bot explains that since no project management is involved, any answer is fair game
#     - bot explains docs in PR, lightweight project management on GitHub, explicitly calling out project management strategies
#     - asks learner to merge
# 11: on pr.closed (learner merge)
#     - bot creates PR about measuring success
#     - challenge question: what might be some ways to measure success? 
#     - learner votes
# 12: on issue_comment.edited (learner voted)
#     - bot validates, most of the checked answers are probably right
#     - bot references PR docs, talks about measuring strategies
#     - asks learner to merge
# 13: on pr.closed (learner merged)
#     - bot opens final issue, explaining what to do with this repo, includes instructions about forking or cloning
#     - bot congratulates learner on completion, recommends next steps