title: Discover and reuse projects within your organization
tagline: Discover and reuse projects within your organization
description: Discover and reuse projects within your organization
template:
  name: innersource
  repo: innersource-template
before:
- type: createIssue
  title: Welcome
  body: welcome.md

steps:

#1
- title: Close an issue
  description: Close an issue
  event: issues.closed
  actions:
  - type: createPullRequest
    title: Repository ownership and names
    head: repo-owner
    body: repo-owner.md
    action_id: ownerPR
  - type: respond
    with: goto-pr.md
    data: 
      url: '%actions.ownerPR.data.html_url%'

#2
- title: Answer the owner challenge
  description: Answer the owner challenge
  event: pull_request.edited
  actions:
  - type: respond
    with: repo-owner-answer.md

#3
- title: Merge the ownership PR
  description: Merge the ownership PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Create discoverable repos
    head: discoverable-repos
    body: discoverable.md
    action_id: discoverablePR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.discoverablePR.data.html_url%'  

#4
- title: Answer the discoverability challenge
  description: Answer the discoverability challenge
  event: issue_comment.created
  actions:
  - type: respond
    with: discoverability-answer.md

#5
- title: Merge the discoverability PR
  description: Merge the discoverability PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Issue and PR templates
    head: templates
    body: templates.md
    action_id: templatesPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.templatesPR.data.html_url%'

#6
- title: Answer the templates challenge question
  description: Answer the templates challenge question
  event: pull_request.edited
  actions:
  - type: respond
    with: templates-answer.md

#7
- title: Merge the templates PR
  description: Merge the templates PR
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Workflows
    head: workflows
    body: workflows.md
    action_id: workflowsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.workflowsPR.data.html_url%'

#8
- title: Answer the workflows challenge question
  description: Answer the workflows challenge question
  event: pull_request.edited
  actions:
  - type: respond
    with: workflows-answer.md

#9
- title: Project management
  description: Project management
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Managing projects on GitHub
    head: projects
    body: projects.md
    action_id: projectsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.projectsPR.data.html_url%'

#10 
- title: Answer the project management challenge
  description: Answer the project management challenge
  event: pull_request.edited
  actions:
  - type: respond
    with: projects-answer.md

#11
- title: Measuring success
  description: Measuring success
  event: pull_request.closed
  actions:
  - type: createPullRequest
    title: Measuring success
    head: metrics
    body: metrics.md
    action_id: metricsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.metricsPR.data.html_url%'

#12
- title: Answer the success metrics challenge
  description: Answer the success metrics challenge
  event: issue_comment.created
  actions:
  - type: respond
    with: metrics-answer.md

#13
- title: Merge the final PR
  description: Merge the final PR
  event: pull_request.closed
  actions:
  - type: createIssue
    title: Congratulations
    body: congratulations.md
    action_id: congratulationsIssue
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.congratulationsIssue.data.html_url%'